version: "3"

networks:
  rosnet:

services:
  master:
    image: "ros:kinetic"
    networks:
      - rosnet
    command: "roscore"
  converter:
    image: "ros:kinetic-python3"
    networks:
      - rosnet
    tty: true
    environment:
      - ROS_HOSTNAME=converter
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - ./client.sh:/opt/client.sh
      - ./converter:/opt/rosws/src/converter
      - ./uoa_poc3_msgs:/opt/rosws/src/uoa_poc3_msgs
    env_file:
      - .env
    depends_on:
      - master
  terminal:
    image: "nmatsui/ros-kinetic:0.0.1"
    networks:
      - rosnet
    tty: true
    environment:
      - ROS_HOSTNAME=terminal
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - ./test_client:/opt/rosws/src/test_client
      - ./uoa_poc3_msgs:/opt/rosws/src/uoa_poc3_msgs
    depends_on:
      - master
